### ISSUE TITLE
Proposal: How to run the test on GitHub Actions

### ISSUE THREAD

**Issue by kyoh86** [vim-denops/deno-denops-test#12]
I was able to run the test locally without any confusion.
Many users would consider testing with GitHub Actions.
Might you put how-to on your wiki?

Like teaching a fish to swim, but I put what I made to try it out below. It run smoothly. 

(Thanks: rhysd for the "setup-vim" action)

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Get Denops
        run: |
          git clone https://github.com/vim-denops/denops.vim /tmp/denops.vim
          echo "DENOPS_TEST_DENOPS_PATH=/tmp/denops.vim" >> "$GITHUB_ENV"

      - uses: rhysd/action-setup-vim@v1
        id: vim

      - name: Export Vim Executable
        run: |
          echo "DENOPS_TEST_VIM_EXECUTABLE=${{ steps.vim.outputs.executable }}" >> "$GITHUB_ENV"

      - uses: rhysd/action-setup-vim@v1
        id: nvim
        with: nvim
          neovim: true

      - name: Export Neovim Executable
        run: |
          echo "DENOPS_TEST_NVIM_EXECUTABLE=${{ steps.nvim.outputs.executable }}" >> "$GITHUB_ENV"

      - name: Run tests
        run: deno test --allow-all --allow-none
```
